var h,hCaptcha,info,video_id,interval,interval_diff=5,latest_id="",ad_code="",error_count=0,bFrame=!1,iEl=new Image,adcc="glob",enableBetaAds=!1,lastAdRequest=(new Date).getTime(),adcnt=0,convcomp=!1,asecl=5,arell=4;
createRequestObject=function(){var a=null;"undefined"!=typeof XMLHttpRequest&&(a=new XMLHttpRequest);if(!a&&"undefined"!=typeof ActiveXObject)try{a=new ActiveXObject("Msxml2.XMLHTTP"),XMLHttpRequest=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP"),XMLHttpRequest=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(b){try{a=new ActiveXObject("Msxml2.XMLHTTP.4.0"),XMLHttpRequest=function(){return new ActiveXObject("Msxml2.XMLHTTP.4.0")}}catch(d){a=
null}}return a}!a&&window.createRequest&&(a=window.createRequest());return a};hs=function(a){try{a.setRequestHeader("Accept-Location","*")}catch(c){}};g=function(a){return document.getElementById(a)};tstamp=function(){return(new Date).getTime()};
cFrame=function(a,c,b,d){try{if(!0!=bFrame){var f=a+"iiFrm",i=g(a);if(null!=i&&null==g(f)){var e=document.createElement("iframe");e.id=f;e.scrolling="no";e.frameBorder="0";e.frameborder="0";e.width=c+"px";e.height=b+"px";e.border="0";e.style.border="0";i.appendChild(e)}g(f).src=d}}catch(j){}};loadAds=function(){_loadAds(!1)};
_loadAds=function(a){lastAdRequest=tstamp();adcnt+=1;var c=tstamp(),b="http://edge.youtube-mp3.org/acode/"+adcc+"/rectangle.htm",d="http://edge.youtube-mp3.org/acode/"+adcc+"/skyscraper.htm";!0==a&&(b+="?r="+c,d+="?r="+c);cFrame("rad",300,250,b);cFrame("sad",160,600,d)};s=function(a){g("youtube-url").value=a;btnSubmitClick()};
pushItemError=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.INVALID_URL+":</b><br />"+g("youtube-url").value;res()};submitCaptchaCallback=function(){4==hCaptcha.readyState&&("false"==hCaptcha.responseText?displayCaptcha(video_id):"true"==hCaptcha.responseText&&btnSubmitClick())};
submitCaptcha=function(){g("captcha-result").disabled=!0;g("captcha-submit").disabled=!0;var a=new Date;hCaptcha=createRequestObject();a="/api/solveCaptcha/?video_id="+video_id+"&result="+escape(g("captcha-result").value)+"&r="+a.getTime();hCaptcha.onreadystatechange=submitCaptchaCallback;hCaptcha.open("GET",a,!0);hCaptcha.send(null);return!1};
displayCaptcha=function(a){resf();var c=new Date;g("progress_info").className="captcha";g("error_text").style.display="block";g("error_text").innerHTML='<div style="text-align:center"><div style="padding:4px;"><b>Please type in the characters you see below:</b></div><form onsubmit="return submitCaptcha()"><div style="padding:3px;"><img src="/c?video_id='+a+"&r="+c.getTime()+'" style="border:solid 1px #ccc;" /></div><div style="padding:3px;"><input id="captcha-result" type="text" style="font-size:14px; padding:5px; width:190px; font-weight:bold; font-family:Arial;" autocomplete="off" /></div><div style="padding:3px;"><input id="captcha-submit" type="submit" /></div></form></div>';
res()};pushItemMaintenance=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.MAINTENANCE+"</b>";res()};pushItemYTError=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.ERROR+"</b>";res()};
limitError=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.LIMIT+"</b>";res()};utf8Decode=function(a){for(var c="",b=0,d=c1=c2=0;b<a.length;)d=a.charCodeAt(b),128>d?(c+=String.fromCharCode(d),b++):191<d&&224>d?(c2=a.charCodeAt(b+1),c+=String.fromCharCode((d&31)<<6|c2&63),b+=2):(c2=a.charCodeAt(b+1),c3=a.charCodeAt(b+2),c+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),b+=3);return c};
setAds=function(a){g("v-ads").style.display="block";a=utf8Decode(unescape(a));try{ad_code!=a&&""!=a&&(ad_code=a,g("v-ads").innerHTML=ad_code)}catch(c){}};
checkInfo=function(){if("captcha"==info.status)displayCaptcha(video_id);else if(""!=info.image&&(g("image").style.display="block",g("image").innerHTML='<img src="'+info.image+'"/>'),""!=info.title&&(g("title").style.display="block",g("title").innerHTML=_ytmp3Lang.TITLE.replace("$0",info.title)),""!=info.length&&(g("length").style.display="block",g("length").innerHTML=_ytmp3Lang.LENGTH.replace("$0",info.length)),""!=info.status&&"pending"!=info.status&&("converting"==info.status?(g("progress").style.display=
"block",g("progress").innerHTML=_ytmp3Lang.CONVERTING):""!=info.progress&&""!=info.progress_speed&&(g("progress").style.display="block",g("progress").innerHTML=_ytmp3Lang.PROGRESS.replace("$0",info.progress).replace("$1",info.progress_speed))),""!=info.ads&&setAds(info.ads),"serving"==info.status&&(g("status_text").innerHTML=_ytmp3Lang.CONVERTED,g("title").style.display="block",g("length").style.display="block",g("loader").style.display="none",g("dl_link").style.display="block",g("progress").style.display=
"none",g("dl_link").innerHTML='<a href="/get?video_id='+video_id+"&h="+info.h+"&r="+tstamp()+'"><b>'+_ytmp3Lang.DOWNLOAD+'</b></a> &middot; <a href="#" onclick="showLinkBox(); return false;">'+_ytmp3Lang.LINKIT+"</a>",g("progress_info").className="success",res()),""!=info.pf)try{iEl.src!=info.pf&&(iEl.src=info.pf)}catch(a){}};
infoRehashCallback=function(){4==h.readyState&&("$$$ERROR$$$"==h.responseText?pushItemError():500==h.status?(error_count+=1,4<error_count&&pushItemMaintenance()):(eval(h.responseText),checkInfo()))};infoRehash=function(){var a=new Date;h=createRequestObject();a="/api/itemInfo/?video_id="+video_id+"&ac=www&r="+a.getTime();h.onreadystatechange=infoRehashCallback;h.open("GET",a,!0);hs(h);h.send(null)};
startInfoRehash=function(a){video_id=a;infoRehash();interval=window.setInterval("infoRehash()",1E3*interval_diff)};pushItemCallback=function(){4==h.readyState&&("$$$ERROR$$$"==h.responseText?pushItemError():"$$$LIMIT$$$"==h.responseText?limitError():500==h.status?pushItemMaintenance():startInfoRehash(h.responseText))};getBF=function(){return!0==bFrame?"true":"false"};
pushItem=function(){var a=new Date;h=createRequestObject();a="/api/pushItem/?item="+escape(g("youtube-url").value)+"&xy=yx&bf="+getBF()+"&r="+a.getTime();h.onreadystatechange=pushItemCallback;h.open("GET",a,!0);hs(h);h.send(null)};strStartswith=function(a,c){return a.substr(0,c.length)==c};
btnSubmitClick=function(){!0==enableBetaAds&&!0==convcomp&&(tstamp()-lastAdRequest)/1E3>asecl&&adcnt<=arell&&_loadAds(!0);convcomp=!0;g("youtube-url");res();resf();info=video_id=null;g("submit").disabled=!0;g("youtube-url").disabled=!0;pushItem();g("progress_info").className="normal";g("progress_info").style.display="block";g("loader").style.display="block";g("status_text").style.display="block";g("status_text").innerHTML=_ytmp3Lang.PROCESSING;return!1};
res=function(){clearInterval(interval);interval=h=null;g("submit-form").onsubmit=btnSubmitClick;g("submit").onclick=btnSubmitClick;g("submit").disabled=!1;g("youtube-url").disabled=!1};resf=function(){g("status_text").style.display="none";g("dl_link").style.display="none";g("title").style.display="none";g("length").style.display="none";g("image").style.display="none";g("loader").style.display="none";g("error_text").style.display="none";g("link_box").style.display="none"};
cutTo=function(a,c){var b=a.indexOf(c);return-1<b?a.substring(0,b):a};getArg=function(a,c){var b=a.indexOf(c+"=",0);return-1<b?(b+=1+c.length,b=a.substring(b),b=cutTo(b,";"),b=cutTo(b,"?"),b=cutTo(b,"&")):null};checkForHash=function(){var a=getArg(window.location.hash,"v");null!=a&&a!=latest_id&&(s("http://www.youtube.com/watch?v="+a+"&ft=li"),latest_id=a);window.setTimeout("checkForHash()",750)};fixDisp=function(){try{g("rad").style.paddingTop="6px",g("sad").style.paddingTop="6px"}catch(a){}};
init=function(){g("submit-form").onsubmit=btnSubmitClick;g("submit").onclick=btnSubmitClick;g("submit").disabled=!1;g("youtube-url").disabled=!1;g("link_box_title").innerHTML=_ytmp3Lang.LINKIT;g("link_box_bb_code_title").innerHTML=_ytmp3Lang.BBCODELINK;g("link_box_html_code_title").innerHTML=_ytmp3Lang.HTMLCODELINK;g("link_box_direct_code_title").innerHTML=_ytmp3Lang.DIRECTCODELINK;checkForHash();fixDisp()};sAll=function(a){a.focus();a.select()};
showLinkBox=function(){if("none"==g("link_box").style.display){var a="http://www.youtube-mp3.org/#v="+video_id;g("BBCodeLink").value="[url="+a+"]"+info.title+"[/url]";g("HTMLLink").value='<a href="'+a+'">'+info.title+"</a>";g("DirectLink").value=a;g("link_box").style.display="block"}else g("link_box").style.display="none"};iFrameRefresh=function(){resf();g("frame").style.display="block"};